suda/tool-bar

lib/toolbar-view.coffee
lib/toolbar.coffee
styles/toolbar.less

I never liked how the toolbar size was fixed, when the icons size could be changed. This PR addresses that issue and adds a new size, together with some clean up.
This PR contains:
Might fix https://github.com/suda/toolbar/issues/2 & https://github.com/suda/toolbar/issues/4
Great package!

Improved icon sizes

---

lib/toolbar-view.coffee

When switching toolbar position, leftover panel elements aren't removed (only the toolbar is), cluttering the DOM tree.
This PR will store the new panel and destroy it before repositioning. It also fixes repositioning when not visible checked.
Fixes #22
Sorry for so many PR. It's a very great and useful package, that just needs a few tweaks and new features. :smile:

Remove leftover panel elements. Fixes #22

---

lib/toolbar-button-view.coffee

`atom.workspaceView` is deprecated. 
Fixes #8 and fixes #18.

atom.workspaceView is deprecated. Fixes #8 and fixes #18

---

lib/toolbar-button-view.coffee
lib/toolbar-view.coffee
lib/toolbar.coffee
styles/theme-atom-dark-ui.less
styles/theme-atom-light-ui.less
styles/theme-flatland-dark-ui.less
styles/theme-one-dark-ui.less
styles/theme-one-light-ui.less
styles/toolbar.less

This PR contains improvements for a better design and layout of the toolbars. The design is now better integrated into the standard themes. I rewrote all classes to `tool-bar-*` to keep in sync with the [status-bar](https://github.com/atom/status-bar/blob/master/lib/status-bar-view.coffee#L7). And I also removed the ID's to make multiple toolbars possible in the future.
A picture is worth a thousand words:
Closes #19
TODO:
~~This is still work in progress (WIP), but~~ I love to hear what you think...

Toolbar theme. Closes #19

---

lib/toolbar-view.coffee
menus/toolbar.cson
package.json

This PR adds the toolbar position option to both Atom's main menu & toolbar contextmenu.
To make that possible, I added 4 more commands and fixed a bug where toolbar position was called to many times.
The main menu makes use of the undocumented radio-menu-items, which the contextmenu doesn't have ([yet](https://github.com/atom/atom/issues/6517)).

Add toolbar position to Atom menu & toolbar contextmenu

---

lib/tool-bar-button-view.coffee

Current `dispatch` target `document.activeElement` isn't work on some commands.
So I changed it :)
I tested this `target` with any commands.
For example, `pane:split-right`, `bookmarks:toggle-bookmark` and more.
And it worked.

Fixed callback target

---

styles/tool-bar.less

Fixes: https://github.com/suda/tool-bar/issues/38
This PR will wrap buttons to a new row on horizontal toolbars and scroll the toolbar on vertical toolbars.
Big thanks to @simurai for his help :clap:

Buttons overflow/wrap. Fixes #38

---

lib/tool-bar-button-view.coffee

Continuing from https://github.com/suda/tool-bar/issues/68, this changes the tooltip's placement based on the toolbar's position.
The tooltip's position is opposite the toolbar, e.g. if the toolbar is on the left, the tooltip is on the right.

Change tooltip placement based on toolbar position

---

lib/tool-bar-view.coffee
styles/tool-bar.less

This PR adds gutter shadow for vertical tool-bars when it overflows.
Ref: https://github.com/suda/tool-bar/issues/38
| Bottom | Top | Bottom & Top | Dark theme |
| --- | ---- | ---- | ---- |
| ![2015-05-31 23_31_11-tool-bar-view coffee - atom](https://cloud.githubusercontent.com/assets/55841/7904011/39a5fec8-07ed-11e5-802e-67bd12e88269.png) | ![2015-05-31 23_33_36-tool-bar-view coffee - atom](https://cloud.githubusercontent.com/assets/55841/7904022/7fa59302-07ed-11e5-8f90-b49a753d6e46.png) | ![theme light](https://cloud.githubusercontent.com/assets/55841/7946765/ded8b7c8-0978-11e5-9e6a-3bdd5cbd2741.png) | ![theme dark](https://cloud.githubusercontent.com/assets/55841/7946769/e60ddd34-0978-11e5-9efb-5b94f800fca4.png)
This is just an idea :bulb: taken from the [Gutter …

Show gutter shadow on vertical scrolling

---

styles/theme-isotope-light-ui.less
styles/theme-isotope-ui.less

Fixes #75 
Better support for Isotope UI themes:
* [Isotope UI theme](https://github.com/braver/isotope-ui)
* [Isotope Light UI theme](https://github.com/braver/isotope-light-ui)
Thanks to @k2b6s9j for reporting and providing the style changes.

Better support for Isotope UI theme

---

README.md
lib/tool-bar-button-view.coffee
lib/tool-bar-manager.coffee
lib/tool-bar-view.coffee
lib/tool-bar.coffee
spec/tool-bar-spec.coffee

The first part of this PR fixes a few memory leaks around DOM event handlers and disposing of subscriptions.
The second part of this PR adds a for consumers to do cleanup when `tool-bar` is deactivated (e.g. during an upgrade).

Fix memory leaks and add onDidDestroy (Fixes #96)

---

CHANGELOG.md
README.md
lib/tool-bar-button-view.coffee
spec/tool-bar-spec.coffee

Make it possible to setup multiple modifiers for one button. With this code it's possible to execute another callback when you click the button while holding the <kbd>alt</kbd>, <kbd>ctrl</kbd> or <kbd>shift</kbd> button.
Closes https://github.com/suda/tool-bar/issues/44.
```coffeescript
@toolBar.addButton
icon: 'octoface'
callback: 
'': 'application:cmd-1'  # Without modifiers is default action
'alt': 'application:cmd-2'
'ctrl': 'application:cmd-3'
'shift': (data) -> console.log data  # With function callback
'alt+shift': 'application:cmd-5'  # Multiple modifiers
'alt+ctrl+shift': 'application:cmd-6'  # All modifiers
data: 'Hello World'
```
When no modifier or non-defined modifier combination is pressed, the default callback (defined by the empty key) is executed.
@suda, @cakecatz, …

Callback modifiers. Closes #44

---

styles/tool-bar.less

Adding the header/footer panels https://github.com/atom/atom/pull/9274 to Atom's core breaks scrolling in tool-bar. It will probably land in Atom `1.6`. Plus tool-bar overlaps any other footer packages:
Most packages aren't affected, but tool-bar's selector beats [core](https://github.com/atom/atom/blob/127e4dbae404257f14e8a050c44c56964902c8ac/static/panels.less#L64-L68) in specificity.
This PR fixes it by moving the `height: 100%;` to a less specific selector. `.tool-bar.tool-bar-16px.tool-bar-vertical` -> `.tool-bar-vertical`. Once `1.6` is out, it could also be removed.

Fix scrolling

---

lib/tool-bar-button-view.coffee
lib/tool-bar-manager.coffee
styles/tool-bar.less

This is ~~a WIP **draft**~~ to align tool-bar items (button & spacer) to the end of the tool-bar. On the horizontal to the right, on the vertical to the bottom. Items can be aligned to the end by using a negative value of the `priority` property.
Tries to fix #93 
~~Am not sure if this is the way to go or use `addLeftTile` & `addRightTile` like the status-bar package. Need to do some more thinking and testing.~~
Code used for testing:
```coffee
@toolBar.addButton
icon: 'arrow-circle-o-right'
callback: 'application:new-file'
iconset: 'fa'
priority: -50
@toolBar.addButton
icon: 'folder'
callback: 'application:open-file'
iconset: 'ion'
priority: -51
@toolBar.addSpacer
priority: -52
@toolBar.addButton
icon: 'archive'
callback: 'core:save'
iconset: 'ion'
priority: -53
```

Align items to the end

---

lib/tool-bar-view.coffee

This will fix random ordering buttons when no priority was specified.
The previous situation was that it copied the priority from the last button/spacer. This could be from the same group (thus package) or from an other group. Resulting in buttons with the same priority from multiple groups ordered by first come.
New situation is that it will increment the priority from the last appended button/spacer that isn't part of the current group, making sure that all button/spacer without priority are at least grouped together.
The real fix is of course just to give all buttons/spacers in your package an priority:

Increment priority by group

---

appveyor.yml
circle.yml

So we [already](https://github.com/suda/tool-bar/pull/63) have [Travis CI](https://travis-ci.org/suda/tool-bar), this PR will add [Appveyor](http://appveyor.com/) and [CircleCI](https://circleci.com) too.
Previous [PR](https://github.com/suda/tool-bar/pull/120) added Linux to Travis CI, which already ran on OSX. Appveyor tests on Windows and CircleCI also runs on Ubuntu Linux.
All CI follow the instructions provided by [Atom Package CI Scripts](https://github.com/atom/ci).
For this to work on this project (PR's and branches, not forks) we need you, @suda, to register the CI accounts:

:shirt: CI

---

lib/tool-bar-view.coffee
lib/tool-bar.coffee
spec/tool-bar-spec.coffee

Closes #91
This will add a new setting to extend the tool bar full width horizontal, forcing it above or below the tree view. As the tool bar is for the whole workspace (and not just the editor pane), and all programs follow that convention, the default for this setting is `true`.
:rotating_light: **Note:**
This PR requires https://github.com/atom/atom/pull/9274, ~~which has been merged into Atom beta, but not in stable. Let's wait for this to go public first.~~
:green_heart: ~~As expected beta channel is passing, stable is failing.~~ All green.

:sparkles: Full width header & footer tool bar. Closes #91

---

styles/theme-atom-dark-ui.less
styles/theme-atom-light-ui.less
styles/theme-one-dark-ui.less
styles/tool-bar.less

:bug: Restore left/top margin on first btn that's not end-aligned
:fire: Removed deprecated code. Fixes https://github.com/suda/tool-bar/issues/133
:bug: Fixed disabled button style
:bug: Restore original button style

Some theme fixes

---

lib/tool-bar-button-view.js
lib/tool-bar-manager.js
lib/tool-bar-spacer-view.js
lib/tool-bar-view.js
lib/tool-bar.js
package.json
spec/tool-bar-legacy-spec.js
spec/tool-bar-spec.js

This is a pretty big breaking change. In [Nuclide](https://github.com/facebook/nuclide), we definitely assume that the return value of `addButton` is a space-pen view. I can imagine that this is the case for a lot of other people. Up to what point should this be mitigated? E.g.: should `ToolBarButtonView` fake having a property `0` so you can grab the underlying element like that?
There's a lot of room for improvement and performance now that space-pen is gone, but I'll do that in a follow-up PR. This is just a first-pass port.

[RFC] Remove space-pen

---

CHANGELOG.md
styles/theme-one-dark-ui.less
styles/theme-one-light-ui.less

This restores bottom-border for vertical tool-bars with the One theme. Closes #157

Full-width is the new standard for the status-bar

---

lib/tool-bar-view.js
menus/tool-bar.cson

As the Tool Bar is part of the visible UI of Atom, I felt like we should move the toggle command to the View menu of Atom.
This PR also removes the Tool Bar Position menu, as it's already available as context-menu on the Tool Bar and as setting.
By moving the Toggle Tool Bar menu-item, I also removed the `&` (Ampersand) from the label to fix https://github.com/suda/tool-bar/issues/97.

Moved menu from Packages to View

---

package.json

This makes sense now since #165 assumes that `atom.workspace.addHeaderPanel` exists. This will prevent people on old Atom versions from accidentally updating/installing tool-bar. Though, given how aggressive Atom's autoupdate is, nobody is probably using anything but the latest.

Limit engines to >=1.6.0

---

lib/raf-debounce.js
lib/tool-bar-view.js

See https://github.com/suda/tool-bar/pull/163#issuecomment-250292271.
This is a first step towards batching DOM updates. Although this is a huge improvement over the current setup, it can be done much better. Right now, all the work is still happening upfront it's just debounced.
From: https://github.com/facebook/nuclide
Before:
After:
This takes init time from 127ms to 55ms.
cc: @jerone

Debounce `drawGutter` with `requestAnimationFrame`

---

styles/theme-one-dark-ui.less
styles/theme-one-light-ui.less

The One themes now handle the borders/padding of panels, so tool-bar doesn't have to worry about it. Thus this PR removes them. Ref:
- https://github.com/atom/one-light-ui/pull/69
- https://github.com/atom/one-dark-ui/pull/162
Also, it adds the same `.disabled` styles from One dark to One light.
The changes will land in Atom `1.11`.

Update One themes

---

lib/tool-bar-button-view.js
spec/tool-bar-spec.js

A little known feature of Atom tooltip is that it supports displaying the keybinding directly inside of the tooltip if you pass a `keyBindingCommand` value as the atom command.
In Nuclide we're already giving the command so I figured it would be cool to display the keybinding as well :)
Let me know if it's something you'd consider! Thanks
Test Plan:
Open Nuclide, mouse over all the buttons, make sure you can see the keybinding for it.

Display keybinding in the tooltip

---

README.md

Had to search the issue tracker to find out this is even possible.

Added example for multiple callbacks

---

README.md
lib/tool-bar-button-view.js
lib/tool-bar-manager.js
lib/tool-bar.js
lib/touch-bar-manager.js

This PR adds support for MacBook Pro Touch Bar. Due to Touch Bar limitations, it can only display seven buttons but that should be enough for most cases.

Add Touch Bar support

---

lib/tool-bar-button-view.js
styles/tool-bar.less

This allows consumers to implement toggle buttons or radio groups.  See #43 
The logic of toggling the selection is left to the consumer.  For a most basic toggle button:
```js
export default {
toolBar: null,
toggleButton: null,
consumeToolBar(getToolBar) {
this.toolBar = getToolBar('my-toolbar');
this.toggleButton = this.toolBar.addButton({
icon: 'plug',
callback: () => this.toggleButton.setSelected(!this.toggleButton.getSelected())
});
}
```

Add support for selected buttons.

---

README.md
lib/tool-bar-button-view.js
spec/tool-bar-spec.js

Allows the tooltip option to be a string or object
fixes #182 
fixes https://github.com/cakecatz/flex-toolbar/issues/96

allow tooltip to be an object

---

lib/tool-bar-button-view.js
spec/tool-bar-spec.js

This will allow the user to use `this.getSelected()` in the function callback

set this as button in callback function

---

lib/tool-bar-button-view.js

Rather than tracking the previously focused element, don't take
focus in the first place.
This avoids a few error cases:
1. Returning focus can have unintentional side effects.
2. Theoretically focus could change between the time a user moused into
the tool bar and when they actually clicked.
Resolves #235

Avoid taking focus when clicking buttons

---

spec/tool-bar-spec.js

The tool bar is never actually added to the DOM, so the `.focus()` call
does not actually do anything.
If this test were working as expected, it should have failed on https://github.com/suda/tool-bar/pull/239.

Remove ineffective focus test

---

lib/tool-bar-button-view.js

Accidentally removed in #239.
Fixes #244
Test plan: In the console issue `document.body.focus()` click the "Upload" button that PlatformIO adds to Tool Bar. Check that the build is run.

Ensure target is within atom-workspace

---

lib/tool-bar-button-view.js

The change I'm proposing allows users to specify both atom commands and function for callback when multiple callbacks are specified. So, before it was only possible to do:
```js
toolBar.addButton({
type: "button",
icon: "chevron-right",
callback: ['application:cmd-1', 'application:cmd-2'],
tooltip: "Show project"
})
``` 
But not with a command and function, like:
```js
toolBar.addButton({
type: "button",
icon: "chevron-right",
callback: ['application:cmd-1', () => console.log("Hello world!")],
tooltip: "Show project"
})
``` 
With this Pull Request that is now possible.
I changed the "executeCallback" function so that the user can use both strings (for atom command dispatching) and function (for whatever the user wants) when the `callback` option is set to an array.
To achieve this I …

Combine string and function callback for button view

---

package.json
spec/tool-bar-spec.js

As mentioned in the Atom documentation, `activationHooks` (or `activationCommands`) will improve startup performance by deferring the package activation. Since this package is grammar agnostic, the `core:loaded-shell-environment` hook is the only suitable one.

Add activationHook

---

README.md

Inspired by #286, this updates the list of plugins and packages using this toolbar:
- Toolbar Almighty: [the repo](https://github.com/varemenos/atom-toolbar-almighty) has been archived by it's owner and will not therefore not receive any updates in the future.
- Toolbar Shortcuts: [the repo](https://github.com/JostCrow/atom-toolbar-shortcuts) has been archived by it's owner and will not therefore not receive any updates in the future.
- Facebook Nuclide: [the package](https://atom.io/packages/nuclide) has been removed (that links returns a 404).

Remove unmaintained plugins and packages

---

README.md
lib/tool-bar-button-view.js
spec/tool-bar-spec.js

Closes #271, this would allow users to add any class(es) to buttons. They can then define the class in a local stylesheet an customize buttons as they see fit.
They can do this through the `class` option which can be either a string or an array of strings. If it is an array every string will be added separately.
~~Arguably this is unnecessary as you can add multiple strings simply by putting spaces in the string.~~ This is not possible with the current implementation, but an be implemented instead if desired.
Example usage:
```js
toolBar.addButton({
icon: 'octoface',
callback: 'application:about',
class: 'my-awesome-class'
});
toolBar.addButton({
icon: 'octoface',
callback: 'application:about',
class: ['multiple', 'classes', 'also', 'works']
});
```

Add any class to a toolbar button

---

README.md
lib/tool-bar-view.js
lib/tool-bar.js
styles/tool-bar.less

- Adds icons size of 18,21,28
- Setting default size to 21
Derived from https://github.com/suda/tool-bar/pull/218

Allowing more iconsizes

---

@types/config.d.ts
@types/index.d.ts

This adds types for tool-bar public API. 
However, since this package is not an `npm` package, we should either push this to [@types/atom](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/atom)
or make a separate `@types/tool-bar`. 
I prefer the first option, `../index` is refering to that file.
Either way, it is good to keep a copy of that file here.
See this in action here: https://github.com/aminya/juno-plus

Type declarations for TypeScript

---

lib/items/tool-bar-button-view.js
lib/raf-debounce.js
lib/tool-bar-view.js

This refactors the code base based on [the issues from Code Climate](https://codeclimate.com/github/suda/tool-bar/issues) regarding code duplication and code complexity. This should get us from a **C** to a (not perfect) **A** :smiley: 
When reviewing this Pull Request, I'd suggest going through the commits one-by-one to see if you agree with every refactoring step that I took. I think that looking at the final diff may be a bit confusing and the motivation for certain refactoring choices may be unclear.

Refactor to decrease code duplication and complexity

---

package.json
spec/tool-bar-spec.js

Tool-bar late loading does not look good. It makes the Atom look bulky. I think 20ms is not that long to defer it.

Remove activation hook

---

lib/touch-bar-manager.js

On my installation, the touch bar didn't originally work. After looking at the Electron documentation, I noticed that the TouchBar API is still experimental. Comparing the code of this library to a working example, I have determined that the fix is to wrap 'items' within an object when it is passed to the TouchBar constructor. This PR contains that change.

Update to current TouchBar Electron API

---

lib/tool-bar.js

deactivate throw the following error on windows.
```
Error deactivating package 'tool-bar' TypeError: Cannot read property 'destroy' of null
```

fix deactivate
