lib/toolbar-view.coffee
lib/toolbar.coffee
package.json

So that you can do something with the return value (e.g. assign a marker class to the created spacer)

Spacer return fix

---

lib/toolbar-button-view.coffee

Add real tooltip. Fixes #13

---

lib/toolbar-view.coffee
styles/toolbar.less

Make toolbar the most left panel. Fixes #20

---

lib/toolbar-button-view.coffee
lib/toolbar.coffee
styles/toolbar.less

Toolbar buttons are now Bootstrap buttons, which adds focus and pressed state.

Added pressed button state

---

styles/theme-one-dark-ui.less
styles/theme-one-light-ui.less

The One themes will be changed so that the negative margin is not needed anymore.

Fix margin in One themes

---

styles/tool-bar.less

Removed buttons outline on focus

---

README.md
lib/tool-bar-view.coffee
menus/tool-bar.cson

Renamed commands

---

.coffeelintignore
coffeelint.json
lib/tool-bar-button-view.coffee
lib/tool-bar-view.coffee
package.json

http://www.coffeelint.org
Should be run before submitting any new content: `coffeelint .`

Implement CoffeeLint

---

lib/tool-bar.coffee
package.json

Rename service provider

---

CHANGELOG.md
lib/tool-bar.coffee
package.json

Remove deprecated API

---

lib/tool-bar-button-view.coffee
spec/tool-bar-spec.coffee

#87 
This PR is restore focus when clicked toolbar button.

Restore focus when clicked button. Fixed #87

---

spec/tool-bar-spec.coffee

:white_check_mark: Added some missing specs and updated existing
TODO:

Added some missing specs and updated existing

---

CHANGELOG.md
lib/tool-bar-button-view.coffee

- :bug: Fixed command-palette:toggle not working. Fixes #105 
- Refactor some code to private methods

Fixed command-palette:toggle not working. Fixes #105

---

lib/tool-bar-button-view.coffee
spec/tool-bar-spec.coffee

Stop event bubbling when click tool-bar button.

---

.remarkignore
.remarkrc
.travis.yml
CHANGELOG.md
README.md
package.json
scripts/remark-lint.sh

No code changes, no documentation changes, only MarkDown linting. One-time overhaul. 
Linting will be done for every following PR on Travis.
Run manually on dev with:
```bash
remark .
```

:shirt: Markdown linter

---

package.json

For all contributors. 
Call with `npm run lint`

:shirt: Added lint script to package.json

---

package.json

:package: Update dependencies

---

.travis.yml

Follow templates for building Atom package and running its specs: https://github.com/atom/ci

:green_heart: Run beta specs on Travis

---

CHANGELOG.md

:memo: Follow the Keep a Changelog convention

---

appveyor.yml

> `https://github.com/atom/ci/pull/38`

Set AppVeyor clone depth

---

README.md
package.json

Includes docs for #121 so can be merged after it.

Docs improvements

---

styles/tool-bar.less

This is a minor change but it looks better to me.

Add transparency fadeout to spacers.

---

CHANGELOG.md
lib/tool-bar-view.js

Fixed wrong calculation for gutter shadow

---

lib/tool-bar-button-view.js
lib/tool-bar-manager.js
lib/tool-bar-spacer-view.js
lib/tool-bar-view.js
lib/tool-bar.js
spec/tool-bar-spec.js

While working on batching DOM ops, these things caught my eye, so I figured I'd factor them out since they're pretty safe and unrelated.
cc: @jerone

Housekeeping

---

lib/tool-bar-button-view.js
spec/tool-bar-spec.js

allow multiple commands in an array

---

lib/tool-bar-button-view.js

Whoops. Overlooked this in #239.

Remove mousedown event listener

---

lib/tool-bar-button-view.js
lib/tool-bar-view.js
package-lock.json
package.json
spec/tool-bar-spec.js

This Pull Requests merges fixes for the build errors in #272 into #272

Fix build error for #272

---

README.md

* Adding Juno Plus to plugins (TypeScript example)
* Move archived packages lower
If there are better plugins, we should add them to the list and remove the unmaintained packages.

Update plugins in the readme

---

.eslintrc.json
@types/config.d.ts
@types/index.d.ts
lib/items/tool-bar-button-view.js
lib/items/tool-bar-spacer-view.js
package-lock.json
package.json

Updated types for tool-bar
PS: added a 14px option so later I make a PR for that one: https://github.com/suda/tool-bar/issues/288

Type declarations

---

lib/tool-bar-view.js
lib/tool-bar.js

Fixes https://github.com/suda/tool-bar/issues/303

useGutter option
